In [1]:
import pandas as pd
import nltk

In [2]:
reviews = pd.read_csv('dataset/small_corpus.csv')

/Users/jasonwintery/opt/anaconda3/envs/metis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
reviews.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1.0,True,"12 25, 2015",ABKWZO2J7RB5C,B00X6ZUZME,Jon.M.Barter,Weak sauce accessory. Had to hold down button...,There sare definitely better options out there,1451001600,NaN,NaN,NaN
1,1.0,True,"08 8, 2016",A1BQU8JLXS6OOX,B015YE7SM4,Richy Fukushima,"I got this mouse on sale. It looks nice, has ...","nice product, but it freezes randomly",1470614400,NaN,NaN,NaN
2,1.0,False,"02 17, 2011",A2Z6E2JHMTJJR4,B001CD8L1Y,Heez,I bought this product from a different website...,Piece of junk.,1297900800,NaN,NaN,NaN
3,1.0,True,"01 4, 2018",A2Y3RL6NN4CI9D,B00CAUTK0E,Mason Rickert,Way overpriced. Hurt with a headset on. And wa...,"Overpriced, save your money and find a better,...",1515024000,2,"{'Color:': ' Onyx', 'Style:': ' Standard Packa...",NaN
4,1.0,False,"09 17, 2010",A25HX4LNZLJNWD,B002BS47TE,mazinger4,"I purchased this game over a month ago, and ev...",Boss difficulty is unbeatable,1284681600,4,{'Format:': ' Video Game'},NaN

In [4]:
reviews.tail()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
69995,5.0,False,"08 28, 2007",A18RQ2URRGIIEA,B000O5TJTE,M. Hart,Having played each of the various video games ...,"A Fun, Challenging, Goal-Oriented & Character-...",1188259200,21.0,{'Platform:': ' Xbox 360'},NaN
69996,5.0,True,"11 27, 2016",A3SN0K4X6ON6FN,B01GWGXBV0,DORNELLE,Great!!! Work perfectly,Five Stars,1480204800,NaN,"{'Edition:': ' Standard', 'Platform:': ' Ninte...",NaN
69997,5.0,False,"04 18, 2011",A2HD3FQD7QL19K,B002BSA3EM,Patty,There are so many various games and workouts t...,Fun way to work out!,1303084800,NaN,NaN,NaN
69998,5.0,True,"03 31, 2014",A22JAEOWB0BBII,B00ECOBFA4,starlakai,My kids love this game! My 4 year old son and ...,Cool game,1396224000,NaN,{'Format:': ' Video Game'},NaN
69999,5.0,True,"07 21, 2012",ADC5AQV9HWN9P,B00006C28X,ant,Great Game For playstation 2 . Very fast shipp...,Great Game!!!,1342828800,NaN,NaN,NaN

In [5]:
reviews.sample(10)

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
27628,2.0,True,"01 10, 2014",A2OUQRS5YWXQ38,B00B3PDH5G,Justin,I bought this headset with a few expectations ...,Great Sound. Terrible Microphone.,1389312000,2,NaN,NaN
35640,3.0,True,"11 21, 2016",A1S67OZ5HRDGH5,B00002STXL,Amazon Customer,Thanks,Three Stars,1479686400,NaN,NaN,NaN
5738,1.0,True,"06 28, 2015",AR91UPIV2M7CS,B00HV2CMX8,Tim T.,They stopped working only a couple of months a...,They stopped working only a couple of months a...,1435449600,NaN,NaN,NaN
29159,2.0,True,"05 28, 2015",A3K8PI414CYZOB,B00O06ZN3O,DONT LIKE IT,no,Two Stars,1432771200,NaN,NaN,NaN
33027,3.0,True,"05 13, 2013",AJT510WEA1QHV,B000R3BLA8,Greesemonkey3,This game was ok and didn't get much better. I...,Meh,1368403200,NaN,{'Platform:': ' PlayStation 3'},NaN
58997,5.0,True,"12 15, 2016",A3JW1MHTYJ79JA,B00ZPFLSGK,Murat Roody,"I used it since january 2016, I get any proble...",Five Stars,1481760000,NaN,NaN,NaN
50934,5.0,True,"06 11, 2018",A2RS953AP4F0YT,B01FZ884E0,Zekebob12,Great product for as cheap as it is. It's not ...,Great for the price.,1528675200,NaN,{'Color:': ' Black'},NaN
66552,5.0,True,"06 27, 2015",AWEF0M7XHTQD2,B00FAS1WDG,alex galvan,I rate this a five star because it got here fa...,love this Microsoft product,1435363200,NaN,NaN,NaN
16421,1.0,True,"08 31, 2016",A1EG13JJ6M22F,B00WW0D54E,Miguel,These 2400mAH batteries are horrible. They hel...,Worst purchase in awhile.,1472601600,60,NaN,NaN
57758,5.0,False,"01 2, 2009",A11UXRR3ZBCPAB,B00104KJ4C,Samier,I love playing Lego Indiana Jones with my two ...,Fun & Entreating for Family,1230854400,NaN,{'Format:': ' Video Game'},NaN

In [6]:
from nltk.tokenize import TreebankWordTokenizer
from string import punctuation
import string

In [7]:
tb_tokenizer = TreebankWordTokenizer()

In [8]:
reviews['rev_text_lower'] = reviews['reviewText'].apply(lambda rev: str(rev)
                                                        .translate(str.maketrans('', '', punctuation))
                                                        .replace('<br />', ' ')
                                                        .lower())

In [9]:
reviews[['reviewText', 'rev_text_lower']].sample(5)

,reviewText,rev_text_lower
64012,a good gift,a good gift
58481,"one of the best toys I have in my home,paid fo...",one of the best toys i have in my homepaid for...
5355,This game is worthless. When on the green you ...,this game is worthless when on the green you c...
51806,Great case! Arrived quickly -- even fits my ne...,great case arrived quickly even fits my new 3...
27489,Played it once and then never again.,played it once and then never again

In [10]:
reviews['tb_token'] = reviews['rev_text_lower'].apply(lambda rev: tb_tokenizer.tokenize(str(rev)))

In [11]:
reviews[['reviewText', 'tb_token']].sample(5)

,reviewText,tb_token
45502,Installation quick and easy. Took 20 minutes a...,"[installation, quick, and, easy, took, 20, min..."
24636,no instructions and very unclear how to play a...,"[no, instructions, and, very, unclear, how, to..."
46946,arrived promptly and was exactly what was aske...,"[arrived, promptly, and, was, exactly, what, w..."
48517,It's somewhat ironic that this showed up for m...,"[its, somewhat, ironic, that, this, showed, up..."
51681,This gamepad on the surface looks and feels li...,"[this, gamepad, on, the, surface, looks, and, ..."

In [12]:
from nltk.tokenize.casual import casual_tokenize

In [13]:
reviews['casual_tokens'] = reviews['rev_text_lower'].apply(lambda rev: casual_tokenize(str(rev)))

In [14]:
reviews[['reviewText', 'casual_tokens', 'tb_token']].sample(5)

,reviewText,casual_tokens,tb_token
4520,Was really a good game. My disc was too scratc...,"[was, really, a, good, game, my, disc, was, to...","[was, really, a, good, game, my, disc, was, to..."
41220,I would have given it a 3 star but it's one of...,"[i, would, have, given, it, a, 3, star, but, i...","[i, would, have, given, it, a, 3, star, but, i..."
11048,triggered.,[triggered],[triggered]
64230,After several rows from other sellers I decide...,"[after, several, rows, from, other, sellers, i...","[after, several, rows, from, other, sellers, i..."
31944,Only the thin plate over the face is aluminum.,"[only, the, thin, plate, over, the, face, is, ...","[only, the, thin, plate, over, the, face, is, ..."

Stemming

In [15]:
from nltk.stem.porter import PorterStemmer

In [16]:
stemmer = PorterStemmer()

In [17]:
reviews['tokens_stemmed'] = reviews['tb_token'].apply(lambda words: [stemmer.stem(word) for word in words])

In [18]:
reviews[['tb_token', 'tokens_stemmed']].sample(5)

,tb_token,tokens_stemmed
11555,"[i, purchased, this, stick, with, the, knowled...","[i, purchas, thi, stick, with, the, knowledg, ..."
34444,"[for, the, price, i, am, overall, pleased, the...","[for, the, price, i, am, overal, pleas, the, b..."
48275,"[i, have, the, black, version, of, this, contr...","[i, have, the, black, version, of, thi, contro..."
24932,"[i, must, agree, with, ramair350s, review, i, ...","[i, must, agre, with, ramair350, review, i, wa..."
22353,"[slips, everywhere, carpet, tile, wood, floory...","[slip, everywher, carpet, tile, wood, flooryou..."

Lemmatisation

In [19]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet as wn
from nltk.corpus import sentiwordnet as swn
from nltk import sent_tokenize, word_tokenize, pos_tag

In [20]:
def penn_to_wn(tag):
    if tag.startswith('J'):
        return wn.ADJ
    elif tag.startswith('N'):
        return wn.NOUN
    elif tag.startswith('R'):
        return wn.ADV
    elif tag.startswith('V'):
        return wn.VERB
    return None

In [21]:
lemmatizer = WordNetLemmatizer()

def get_lemmas(tokens):
    lemmas = []
    for token in tokens:
        pos = penn_to_wn(pos_tag([token])[0][1])
        if pos:
            lemma = lemmatizer.lemmatize(token, pos)
            if lemma:
                lemmas.append(lemma)
    return lemmas

In [22]:
reviews['lemmas'] = reviews['tb_token'].apply(lambda tokens: get_lemmas(tokens))

In [23]:
reviews[['reviewText', 'tokens_stemmed', 'lemmas']].sample(5)

,reviewText,tokens_stemmed,lemmas
61345,This game arrived fast and exactly as describe...,"[thi, game, arriv, fast, and, exactli, as, des...","[game, arrive, fast, exactly, described, absol..."
24629,I'll start off by saying that this remote has ...,"[ill, start, off, by, say, that, thi, remot, h...","[ill, start, say, remote, have, good, feature,..."
15754,Middle wheel stopped working after x6 months,"[middl, wheel, stop, work, after, x6, month]","[middle, wheel, stop, work, x6, month]"
31475,Bought this used and it came in rougher shape ...,"[bought, thi, use, and, it, came, in, rougher,...","[bought, use, come, rougher, shape, expect, de..."
326,Please refund my money.. it doesnt work,"[pleas, refund, my, money, it, doesnt, work]","[please, refund, money, doesnt, work]"

Sentiment

In [27]:
def get_sentiment_score(tokens):
    score = 0
    tags = pos_tag(tokens)
    for word, tag in tags:
        wn_tag = penn_to_wn(tag)
        if not wn_tag:
            continue
        synsets = wn.synsets(word, pos=wn_tag)
        if not synsets:
            continue
            
        synset = synsets[0]
        swn_synset = swn.senti_synset(synset.name())
        
        score += (swn_synset.pos_score() - swn_synset.neg_score())
        
    return score

In [24]:
swn.senti_synset(wn.synsets('perfect', wn.ADJ)[0].name()).pos_score()

0.625

In [28]:
reviews['sentiment_score'] = reviews['lemmas'].apply(lambda tokens: get_sentiment_score(tokens))

In [29]:
reviews[['reviewText', 'lemmas', 'sentiment_score']].sample(5)

,reviewText,lemmas,sentiment_score
37044,Fun but not the best they have done.,"[fun, not, best, have, do]",0.500
21403,Could not get it to work.,"[not, get, work]",-0.500
28800,way too quiet,"[way, too, quiet]",-0.625
39750,just disapointed to find out you have to go th...,"[just, disapointed, find, have, go, thru, alot...",0.875
23857,This was the most disappointing thing I have e...,"[be, most, disappoint, thing, i, have, ever, b...",2.625

In [30]:
reviews[['reviewText', 'lemmas', 'sentiment_score']].sample(10)

,reviewText,lemmas,sentiment_score
47262,I'm having a lot fun playing the game. I wish ...,"[im, have, lot, fun, play, game, i, wish, wasn...",2.125
36811,"It's definitely a good game, but I was pretty ...","[definitely, good, game, i, be, pretty, let, d...",4.375
41721,"Biggest draw back, you cannot save your game, ...","[big, draw, back, not, save, game, have, finis...",-2.250
39204,good game but platform games are still provide...,"[good, game, platform, game, be, still, provid...",1.125
59853,Great keyboard!,"[great, keyboard]",0.000
31913,"Very long and completely functional, except it...","[very, long, completely, functional, stop, wor...",1.000
58541,Awesome and work great. I would recommend thes...,"[awesome, work, great, i, recommend, gamer]",0.375
44921,"3 games for 20 dollars is a good deal, but com...","[game, dollar, be, good, deal, compare, unchar...",1.125
63516,"I love this ""game"". It's a mixture of games t...","[i, love, game, mixture, game, require, keep, ...",1.250
68964,Best mouse I've owned. Awesome price too.,"[best, mouse, ive, own, awesome, price, too]",1.375